**Assignment-Week 4_ATADOGA FAVOUR**

### **Question 1**
Demonstrate how to create a 1-dimensional, 2-dimensional, and 3-dimensional numpy arrays using `np.array`. Use any suitable data for the arrays and display each. The 1 dimensional, 2 dimensional and 3 dimensional arrays you created should have shapes of ```(7,), (4, 4), and (3, 2, 3)``` respectively. Print out the shapes of each array after you have created them.

In [2]:
# **Answer to question 1**
import numpy as np

# 1-dimensional array with shape (7,)
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7])
print("1D Array:\n", arr_1d)
print("Shape:", arr_1d.shape)

# 2-dimensional array with shape (4, 4)
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print("\n2D Array:\n", arr_2d)
print("Shape:", arr_2d.shape)

# 3-dimensional array with shape (3, 2, 3)
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]],
                   [[13, 14, 15], [16, 17, 18]]])
print("\n3D Array:\n", arr_3d)
print("Shape:", arr_3d.shape)


1D Array:
 [1 2 3 4 5 6 7]
Shape: (7,)

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Shape: (3, 2, 3)


### **Question 2**

**2a.** Write a Python code to create two arrays using `np.zeros` and `np.ones` with a shape of (4, 5). Print both arrays.\
**2b.** Using the `np.arange` function, create an array from `10 - 36` \
**2c.** Generate a numpy array with `25` linearly spaced values ranging from `20 to 50` using `np.linspace`. Print the array.

In [3]:
# Answers to question 2

# 2a. Creating arrays with np.zeros and np.ones
zeros_array = np.zeros((4, 5))
ones_array = np.ones((4, 5))
print("Zeros Array:\n", zeros_array)
print("\nOnes Array:\n", ones_array)

# 2b. Create an array using np.arange from 10 to 36
arange_array = np.arange(10, 37)
print("\nArray from 10 to 36:\n", arange_array)

# 2c. Generate 25 linearly spaced values from 20 to 50
linspace_array = np.linspace(20, 50, 25)
print("\nLinearly spaced array:\n", linspace_array)


Zeros Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Array from 10 to 36:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36]

Linearly spaced array:
 [20.   21.25 22.5  23.75 25.   26.25 27.5  28.75 30.   31.25 32.5  33.75
 35.   36.25 37.5  38.75 40.   41.25 42.5  43.75 45.   46.25 47.5  48.75
 50.  ]


### **Question 3**

Consider the numpy array below. Write a Python code to extract the sub-array containing the third to fifth elements.
```python
arr = np.array([23, 54, 32, 33, 56, 78, 77, 45, 33])
```

In [4]:
# ANSWER TO QUESTION 3

arr = np.array([23, 54, 32, 33, 56, 78, 77, 45, 33])

# Extracting third to fifth elements (index 2 to 4)
sub_array = arr[2:5]
print("Sub-array (3rd to 5th elements):", sub_array)


Sub-array (3rd to 5th elements): [32 33 56]


### **Question 4**

Given the 2-dimensional numpy array below, demonstrate how to slice and obtain the third row and first and second column.

```python
arr_2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9],
                  [4, 5, 3]])
```

In [5]:
# ANSWERS TO QUESTION 4

arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9],
                   [4, 5, 3]])

# Extract third row and first & second columns
slice_result = arr_2d[2, 0:2]
print("Sliced Array (3rd row, 1st & 2nd columns):", slice_result)


Sliced Array (3rd row, 1st & 2nd columns): [7 8]


### **Question 5**

Given the 3d array below, answer the following questions:\
**5a.** What is the shape of the array and how many layers or blocks does the array have?\
**5b.** Slice out the second and last rows from the third block using array slicing.
```python
array_3d = np.array([
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9], 
     [2, 3, 3]],
    
    [[13, 14, 15], 
     [16, 17, 18], 
     [19, 20, 21], 
     [22, 23, 24]],
    
    [[25, 26, 27], 
     [28, 29, 30], 
     [31, 32, 33], 
     [34, 35, 36]]])
```

In [6]:
# ANSWERS TO QUESTION 5

import numpy as np

array_3d = np.array([
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9], 
     [2, 3, 3]],
    
    [[13, 14, 15], 
     [16, 17, 18], 
     [19, 20, 21], 
     [22, 23, 24]],
    
    [[25, 26, 27], 
     [28, 29, 30], 
     [31, 32, 33], 
     [34, 35, 36]]])

# 5a. What is the shape of the array and how many layers or blocks does it have?
shape = array_3d.shape
num_blocks = shape[0]
print("Shape of the array:", shape)
print("Number of blocks (layers):", num_blocks)

# 5b. Slice out the second and last rows from the third block
# Third block is at index 2; second row index is 1, last row index is -1
sliced_rows = array_3d[2, [1, -1], :]
print("\nSliced rows (2nd and last from 3rd block):\n", sliced_rows)


Shape of the array: (3, 4, 3)
Number of blocks (layers): 3

Sliced rows (2nd and last from 3rd block):
 [[28 29 30]
 [34 35 36]]
